### ISSUE TITLE
Kek is such a scammer

### ISSUE THREAD

**Issue by IamAdminX** [qoft/Dazeer-Spammer#13]
Bro literally doesnt give customers dazeer back because they bought with paypal and his paypal got termed smh...

All the image links are here:

https://imagine.skid.group/Fr/x63bwj4h.png
https://imagine.skid.group/Fr/ffjm4sbs.png
https://imagine.skid.group/Fr/vjj4ob7s.png
https://imagine.skid.group/Fr/ei60uhha.png
https://imagine.skid.group/Fr/7rtbrq90.png

**Comment by kekeds** [comment]
Such a scammer!!😡😡

**Comment by 2l2cgit** [comment]
says the guy who rats customers

**Comment by kekeds** [comment]
> says the guy who rats customers

proof rn

**Comment by Conspiracy12** [comment]
I had lost a lot of coins in some scam case just like this thanks to the best hacker in the world who helped me recover all my funds,message him on telegram his telegram username is https://t.me/Blackhathacker110
